/* This file was automatically generated.  Do not edit! */
int main(int argc,char const *argv[]);
void interactive_mode(Node *root);
Node *stdin_mode(int argc,char const *argv[]);
int std_arg_parser(char *str,char **argv_p[]);
Node *import_data(char const *filename,Node *root,u_int *error_count,u_int *record_count);
Record *parse_line(FILE *file,PARSE_LINE_ERROR_FLAG *error);
FILE *ensure_open_file(char const *filename);
void fatal(const char *msg);
void warn(char *msg);
void print_tree(Node *root);
void print_leafs(Node *leaf_node);
void print_leaf(Node *leaf_node);
void print_layer(Node *left_node);
void print_node(Node *node);
void print_help();
void print_welcome();
Node *insert_into_node_and_split(Node *root,Node *old_node,char *key,u_int index,Node *left_node,Node *right_node);
Node *inesrt_into_parent(Node *root,Node *left_node,char *key,Node *right_node);
void reset_parent(Node *node);
u_int cut(u_int length);
Node *insert_into_leaf_and_split(Node *root,Node *leaf,char *key,u_int insertion_point,Record *record);
void _add_into_node(Node *node,char *key,u_int insertion_point,void *left_node,void *right_node);
void _write_into_node(Node *node,char *key,u_int insertion_point,void *left_node,void *right_node);
void _add_into_leaf(Node *leaf,char *key,u_int insertion_point,void *record);
void _write_into_leaf(Node *leaf,char *key,u_int insertion_point,void *record);
Node *insert_into_leaf(Node *root,Node *leaf,char *key,Record *pointer);
Node *insert_record(Node *root,Record *new_record);
Node *insert(Node *root,char *key,char *value);
Node *init_new_tree(char *key,Record *Record);
Record *find(Node *root,char *key);
Node *find_leaf(Node *root,char *key);
bool b_search_key(u_int *index,void *base,u_int total,char *target,int(*cmp)(char const *,char const *));
int b_search_subtree(void *base,int total,char *target,int(*cmp)(char const *,char const *));
int strcmp(char const *str1,char const *str2);
void memcpy(void *dst,const void *src,u_int length);
void pointer_copy(void **dst,const void **src,u_int length);
void pointer_shift(void **dst,const void **src,u_int length);
void shift_backward(void *dst,const void *src,u_int length);
Node *make_leaf(void);
Node *_make_node(u_int max_key_num,bool is_leaf);
Node *make_node(void);
void free_record(Record *record);
Record *make_record(char *key,char *value);
void print_record(const Record *record);
extern char SEPATATOR;
